### PR TITLE
Fix a few typos in documentation

### PR DESCRIPTION
**Pull request by okellogg**

### CODE REVIEW

**Comment by thvnx** [comment]
As well as for https://github.com/AdaCore/libadalang/pull/951, I'll take care of the merge internally and come back here when done.

**Comment by okellogg** [comment]
Hi @thvnx, thank you for merging https://github.com/AdaCore/libadalang/pull/951

My master appears to have a conflict brought in by changes on AdaCore master - do I need to resolve that?

**Comment by thvnx** [comment]
Hi @okellogg, I'm handling this internally so rebasing your PR is not needed but it would be appreciated at least!

I'll keep you posted, thank you!

**Comment by pmderodat** [comment]
Hello @okellogg,

We have resolved conflicts and merged your work as https://github.com/AdaCore/langkit/commit/15267cdde3d7bd66c5932216e39fee07fe2c5212. Thank you very much for fixing all these typos!

**Pull request closed without merging**
