### PR TITLE
$.Analysis: turn Get_From_*/Get_With_Error preconds into regular code

### PR DESCRIPTION
**Pull request by pmderodat**

### CODE REVIEW

**Review by raph-amiard — COMMENTED** [review]
That's a bit of a weird pattern. Is the thing that we'd like those pre enabled in production builds ? If that's the case, isn't there a way to do just that via `Assertion_Policy` ?

**Comment by pmderodat** [comment]
IIRC, when we discussed this, you also had the argument that contracts are not debug friendly: whole expression evaluates to false => you just get an assertion_failure exception, whereas with explicit checks, you can use a custom exception message.

**Comment by pmderodat** [comment]
Another point in favor of explicit check is that we can share them with other APIs. To achieve this, here I should move the checks to $.Implementation (no point in having contracts here as users won’t see them). What do you think?

**Comment by raph-amiard** [comment]
I agree with everything, especially the point about factoring that in the implem.

I was just thinking about the pattern:

```ada
Pre => Cond or else raise Assertion_Error with "..."
```

That allows to have better diagnostics in pre conditions, but here, factoring in the implem seems even better, especially with the added constraint of prod vs debug.

**Review by raph-amiard — APPROVED** [review]

**Pull request merged**
